runmode: debug                # 开发模式, debug, release, test
addr: :8082                   # HTTP绑定端口
url: http://127.0.0.1:8082   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10            # pingServer函数try的次数
jwt_secret:
session:
  type: redis # file redis
  secret: DSDI@#&#@&$
  name: kronos

tls:
  addr: :8081
  cert: cert/server.crt
  key: cert/server.key
locus:
  path: storage/logs/
  file: access.log
db:
  type: mysql
  dbname: tower
  loc: Asia%2FShanghai
  host: localhost:3306
  charset: utf8mb4
  user: root
  pass: Root_123123
  native: true
  debug: 4 # 1 Silent、2Error、3Warn、4Info
  prefix: wk_

redis:
  host: 127.0.0.1
  port: 6379
  pass:
casbin:
  debug: false